services:
 cassandra:
   image: cassandra:latest
   container_name: cassandra-container
   ports:
     - "8081:8081"
   environment:
     - CASSANDRA_START_RPC=true
   volumes:
     - ./cassandra_data:/var/lib/cassandra